#Enforcing DISA STIG to for Win Server 22
- name: check for non-NTFS or non-ReFS volumes
  tags: volume
  ansible.windows.win_shell:
    Get-Volume | Where-Object { $_.FileSystem -ne 'NTFS' -and $_.FileSystem -ne 'ReFS'}
  register: non_ntfs_volumes

- name: display non-compliant volumes
  tags: volume
  debug:
    var: non_ntfs_volumes.stdout_lines

- name: Ensure NoAutoPlayfornonVolume is set to 1
  tags: WN22-CC-000210,stig,autoplay
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Explorer
    name: NoAutoPlayfornonVolume
    data: 1
    type: dword
    state: present