---
- name: Update APT cache (Debian-based)
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Upgrade all APT packages
  ansible.builtin.apt:
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Update all YUM/DNF packages (RedHat-based)
  ansible.builtin.package:
    name: "*"
    state: latest
  when: ansible_os_family in ["RedHat", "Cent", "Fedora", "AlmaLinux"]
