- name: Update all packages to the latest version
  ansible.builtin.yum:
    name: "*"
    state: latest
# Set up the Docker Enginer repo in Cent
- name: Ensure yum-utils is installed
  ansible.builtin.yum:
    name: yum-utils
    state: present
  
- name: Add Docker Repo
  ansible.builtin.command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker packages
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Run hello-world container to verify Docker installation
  ansible.builtin.command: docker run hello-world
  register: docker_hello
  changed_when: false
  failed_when: "'Hello from Docker!' not in docker_hello.stdout"

- name: Create Home Assistant config directory
  ansible.builtin.file:
    path: "{{ ha_config_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install Python 3 and pip3
  become: yes
  ansible.builtin.yum:
    name:
      - python3
      - python3-pip
    state: present

- name: Install required Python packages with pip3
  become: yes
  ansible.builtin.pip:
    name:
      - docker
      - requests
    executable: pip3

- name: Deploy Home Assistant container
  community.docker.docker_container:
    name: "{{ ha_container_name }}"
    image: "ghcr.io/home-assistant/home-assistant:stable"
    state: started
    restart_policy: unless-stopped
    privileged: true
    network_mode: host
    env:
      TZ: "America/New_York"
    volumes:
      - "{{ ha_config_path }}:/config"
      - "/run/dbus:/run/dbus:ro"
