- name: Install Windows updates
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Install all available Windows updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes